version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "yahya"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      go-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "github.com/gin-gonic/*"
          - "github.com/swaggo/*"
      gin-framework:
        patterns:
          - "github.com/gin-gonic/*"
      swagger:
        patterns:
          - "github.com/swaggo/*"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "yahya"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "yahya"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Frontend dependencies (if using npm)
  - package-ecosystem: "npm"
    directory: "/ui/dashboard"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "yahya"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
    groups:
      react:
        patterns:
          - "react"
          - "react-*"
          - "@types/react*"
      nextjs:
        patterns:
          - "next"
          - "@next/*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "daisyui"
          - "@tailwindcss/*"
      development:
        dependency-type: "development"
        patterns:
          - "*"