version: '3.8'

services:
  # Backend service with embedded BadgerDB
  backend:
    build: .
    image: propguard-backend:latest
    container_name: propguard-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: ${GIN_MODE:-release}
      JWT_SECRET: ${JWT_SECRET}
      VAULT_MASTER_KEY: ${VAULT_MASTER_KEY}
      BADGER_DIR: /app/data
      SERVER_PORT: 8080
    volumes:
      - badger-data:/app/data      # BadgerDB data persistence
      - ./.env:/app/.env:ro         # Environment configuration
    networks:
      - propguard-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend dashboard
  frontend:
    build: ./ui/dashboard
    image: propguard-frontend:latest
    container_name: propguard-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - backend
    networks:
      - propguard-network

volumes:
  badger-data:
    driver: local

networks:
  propguard-network:
    driver: bridge